# Generated by Django 3.1.5 on 2021-01-31 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_auto_20210122_1045"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
            },
        ),
    ]
