# Generated by Django 3.1.5 on 2021-01-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trucks", "0002_auto_20210120_0820"),
    ]

    operations = [
        migrations.AlterField(
            model_name="truck",
            name="payment_methods",
            field=models.ManyToManyField(
                to="trucks.PaymentMethod", verbose_name="Payment Methods"
            ),
        ),
    ]
