# Generated by Django 3.1.5 on 2021-01-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trucks", "0003_auto_20210121_1053"),
    ]

    operations = [
        migrations.AddField(
            model_name="truck",
            name="city",
            field=models.CharField(
                default="Warsaw", max_length=70, verbose_name="City"
            ),
            preserve_default=False,
        ),
    ]
