# Generated by Django 3.1.5 on 2021-03-02 11:03

from django.db import migrations, models

import conf.utils


class Migration(migrations.Migration):

    dependencies = [
        ("trucks", "0004_truck_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="truck",
            name="payment_methods",
            field=models.ManyToManyField(
                blank=True,
                to="trucks.PaymentMethod",
                verbose_name="Payment Methods",
            ),
        ),
        migrations.AlterField(
            model_name="truckimage",
            name="image",
            field=models.ImageField(
                max_length=200,
                upload_to=conf.utils.image_directory_path,
                verbose_name="Image",
            ),
        ),
    ]
